### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by Jacalz** [psanford/wormhole-william#100]
The latest release is [v1.0.6](https://github.com/psanford/wormhole-william/releases/tag/v1.0.6) from December 2021. That will soon be two years ago. A lot has happened since then on the [master branch](https://github.com/psanford/wormhole-william/commits) and I have various open PRs at https://github.com/psanford/wormhole-william/pulls that are waiting for reviews and merge.

It is time to do a new release. Not only does a new release mean rebuilt cmd binaries with all of the security fixes from the new Go compiler releases (assuming #93 is merged) but also that projects like [rymdport](https://github.com/Jacalz/rymdport) get access to all of the features since the last release.

**Comment by gaby** [comment]
@psanford Any plans for a new release? Thanks!

**Comment by psanford** [comment]
I've released 1.0.7

**Comment by gaby** [comment]
@psanford Thank you!
