### ISSUE TITLE
feature request: wormhole code completion

### ISSUE THREAD

**Issue by j-lakeman** [psanford/wormhole-william#105]
I really appreciate the existing command completion!
IMHO it would be even cooler to have a completion for the wormhole code. It could just look up the word in the dictionary, for example.

**Comment by psanford** [comment]
Wormhole code completion works as part of bash/zsh completion:

```
$ wormhole-william receive 2-frequency-ba<TAB>
2-frequency-baboon     2-frequency-backward   
2-frequency-backfield  2-frequency-banjo
```

**Comment by j-lakeman** [comment]
I didn't know about that functionality, cheers! Works with fish shell as well, btw.
But what I meant was the case when typing `wormhole-william receive` + `ENTER`.
Then the completion doesn't work, instead `TAB` inserts `\t`.
I'd prefer to not clutter my shell history with all the different wormhole codes. Is it possible to extend the completion for my case as well?

**Comment by psanford** [comment]
I don't really want to add a thirdparty dependency for a readline-like library for code completion when we already have code completion on the cli.

**Comment by j-lakeman** [comment]
Sounds fair enough.

**Comment by dbohdan** [comment]
I miss completion when I switch between Magic Wormhole on some systems and wormhole-william on others.

> I don't really want to add a thirdparty dependency for a readline-like library for code completion when we already have code completion on the cli.

Would you be open to an implementation of code completion that only used golang.org/x/term? Seems like it should be possible to implement with [`AutoCompleteCallback`](https://pkg.go.dev/golang.org/x/term#Terminal).
