### ISSUE TITLE
Feature request: enable shell completions by default

### ISSUE THREAD

**Issue by j-lakeman** [psanford/wormhole-william#108]
Upon installation, IMHO it would make sense to enable the shell completions by default for any of bash, zsh and fish present.

**Comment by psanford** [comment]
I don't think tools should modify shell configuration files without getting explicit consent from the user. I'd be ok adding a new cli command to install shell completions for you instead (essentially just following the instructions from `wormhole-william  shell-completion -h`, but it would need to be clear that is what the command is doing (probably with a confirmation prompt and a list of files that will be modified showed to the user).

Its fairly common for downstream packages (dpkg, rpm) to include installation of system level shell completion files. That would also be fine with me but would need to be done on a per distribution basis.

**Comment by j-lakeman** [comment]
Fair enough, opened issue downstream.
Thanks for clarification!
