### ISSUE TITLE
Request: prebuilt binary for arm (other than arm64)

### ISSUE THREAD

**Issue by m040601** [psanford/wormhole-william#18]
First of all thank you for your work in this project and especially the thought of releasing the prebuilt binaries

I suppose you have or are using some kind of automated infrastructure or service to do this, so I think this request wouldn't be too much of an extra effort.

But it would be extremely usefull, for getting wormhole on tiny less powerfull computers , SBC boards etc. Think of Raspberrry Pi and alike. It's not practical to download the entire Go chain infrastructure and build on them.

Right now, you do release an arm64. But this only supports the most recent Raspberry Pi's for example. It leaves out an enormous amount of previous devices.

I also know it can be cumbersome to support "all" of arm architectures . Should it be arm5 or armv6 or ... ?

But I've seen from other (go) projects that do this,  that usually all it takes is one single arm (not 64 bit) binary for all of them. Go projects 99% of the time run wonderfully on all them.

So I would like to request if you could provide this.
If a "universal" not 64 bit binary not possible, then at least an armv7h binary for the Raspberry Pi 2.

Thanks in advance

**Comment by psanford** [comment]
Do you have some examples of other go projects that do this?

**Comment by m040601** [comment]
github actions, workflows:
https://github.com/tsl0922/ttyd/tree/master/.github
https://github.com/yudai/gotty/releases/tag/v1.0.1

goreleaser:
https://goreleaser.com/ci/actions/

drone:
https://github.com/techknowlogick/shiori/releases
