### ISSUE TITLE
How To Host A Rendezvous Server?

### ISSUE THREAD

**Issue by bonedaddy** [psanford/wormhole-william#20]
I took a look through the code, cli, and existing examples but i couldn't seem to find anything explaining how to host your own rendezvous server

**Comment by psanford** [comment]
Wormhole-william doesn't implement the rendezvous server. (We do have a rendezvous server implementation for tests but it isn't suitable for running outside of a testing environment right now).

The public default rendezvous server runs this code: https://github.com/warner/magic-wormhole-mailbox-server. Its relatively easy to get up and running by following its readme.
