### ISSUE TITLE
Add wormhole to macports & homebrew

### ISSUE THREAD

**Issue by jasperweiss** [psanford/wormhole-william#25]
I couldn't find wormhole on any of the popular package managers on mac so I had to compile it myself and add it to /usr/local/bin manually. It'd be great if this was on macports and homebrew so people could more easily install it and more importantly, keep it up to date. Especially since the python implementation isn't distributed there either. 

Is this something that anyone would like to look at? Otherwise I'd by happy to do it.

**Comment by psanford** [comment]
If you'd like to be a package maintainer for macports and homebrew feel free to do so.

**Comment by jasperweiss** [comment]
Alright, thanks. I'll post any updates on this issue.

**Comment by jasperweiss** [comment]
This issue is currently blocking me from being able to get it on mac ports:

`Error: go.vendors can't handle dependencies from salsa.debian.org`

See the Portfile I created [here](https://gist.github.com/jasperweiss/6ee2ba48710a7cbee14937cdfe69beff)

**Comment by jasperweiss** [comment]
Wormhole-william is now available on MacPorts. See [Portfile](https://github.com/macports/macports-ports/blob/master/sysutils/wormhole-william/Portfile)

**Comment by Jacalz** [comment]
> Wormhole-william is now available on MacPorts. See [Portfile](https://github.com/macports/macports-ports/blob/master/sysutils/wormhole-william/Portfile)

Should this issue perhaps be closed then? :)

**Comment by j-lakeman** [comment]
Anyone interested in adding it to Homebrew as well?

**Comment by jiripospisil** [comment]
> Anyone interested in adding it to Homebrew as well?

[Added](https://github.com/Homebrew/homebrew-core/blob/master/Formula/w/wormhole-william.rb) as of an hour ago.

```
brew update && brew install wormhole-william
```
