### ISSUE TITLE
Specify message on the command line?

### ISSUE THREAD

**Issue by oscarfroberg** [psanford/wormhole-william#6]
I'm really glad to have found a Go version of Magic Wormhole! This makes installation a breeze by being able to simply download a single binary from my private server.

Small issue so far though while trying it out: With Magic Wormhole I can do
```
wormhole send --text "hello"
```
or even piping, like
```
ls -1 | wormhole send --text -
```
but neither of these seem to work with `wormhole-william`. Am I missing something or if not, are these features in the roadmap?

**Comment by psanford** [comment]
Adding the --text flag seems reasonable to me. I can take a look in the next few days.
