### ISSUE TITLE
Use peer's relay hints

### ISSUE THREAD

**Issue by piegamesde** [psanford/wormhole-william#71]
If peer sends a relay server in their transit hints, that hint should be followed. Otherwise, clients with different configured relay servers cannot find each other over a relay connection. Conversely, the own configured relay server should be sent over as hint (not sure if this is done currently).

**Comment by psanford** [comment]
Aren't we already doing that here? https://github.com/psanford/wormhole-william/blob/master/wormhole/file_transport.go#L187

**Comment by piegamesde** [comment]
Hm, something definitely is fishy in there. Especially since I can reproduce it only while receiving, and not while sending.

Another thing that I noticed by looking at the code (not sure if related, but maybe): Why is the code checking on the `type` field of the inner hints and especially for a `direct-tcp-v1` value? As far as I know, this is not part of the (original) protocol.

**Comment by psanford** [comment]
The python code sets the inner message type to `direct-tcp-v1` here: https://github.com/magic-wormhole/magic-wormhole/blob/master/src/wormhole/_hints.py#L130-L136

wormhole-william checks this on the assumption that the inner message could support alternative types in the future.

I can't reproduce this and don't see anything incorrect in the code. Can you provide steps to reproduce the issue you are seeing?

**Comment by piegamesde** [comment]
> The python code sets the inner message type to direct-tcp-v1 here

Oh, fuck.

The thing is, I didn't know that and it wasn't in the specification. In [magic-wormhole/magic-wormhole-protocols@`af046df` (#16)](https://github.com/magic-wormhole/magic-wormhole-protocols/pull/16/commits/af046dff665d1ca37aec9e36aee7a3fc77576c9a), I therefore added a `type` but with a default value of `tcp` instead of `direct-tcp-v1` (because, frankly, "direct"-something-something makes no sense for a *relay* hint). Also, I incremented the version number to make sure because of backwards compatibility (which, turns out, may not have been necessary if all clients already check `type`.).

> Can you provide steps to reproduce the issue you are seeing?

I think I can now. As before, use two clients that have different relay servers configured, but also the sender side must not provide a `type` field in its inner relay hints.

----

So probably the behavior of the code is mostly "correct" and it is the specification that requires fixing.

**Comment by piegamesde** [comment]
> Aren't we already doing that here?

Apparently not, or at least not when receiving. On the sender side, I get the following JSON: `{"transit":{"abilities-v1":[{"type":"direct-tcp-v1"},{"type":"relay-v1"}],"hints-v1":[]}}`

**Comment by psanford** [comment]
Please provide the steps to reproduce the issue.

**Comment by psanford** [comment]
Does the issue occur for you if you use the python implementation instead of the rust implementation? I tested with the python implementation yesterday and didn't have any issues with using an alternative tcp relay.

**Comment by piegamesde** [comment]
The issue does not occur when testing against the Python implementation because as long as at least one one side sends the hints correctly, they are able to find each other. Things only break down because the Rust implementation has a bug too (it doesn't add the `type` field, so the Go implementation ignores the hints).

**Comment by psanford** [comment]
The receive behavior sounds like its another instance of #57, that wormhole-william doesn't listen on the receiver side for incoming connections today, including via a transit relay. Thus it doesn't publish a transit relay hint since it isn't listening for incoming connections via a relay.

**Comment by piegamesde** [comment]
Tentatively closing as #57. I still think that "not sending the hints" is an issue distinct to "not following the hints", but they may have a common root cause.
