### ISSUE TITLE
64-bit and ARM binaries for Windows

### ISSUE THREAD

**Issue by rollingmoai** [psanford/wormhole-william#77]
I don't see why not provide these too. Besides, Windows 11 is [64-bit only](https://windowsreport.com/windows-10-will-support-only-64-bit-same-as-windows-11/).

**Comment by psanford** [comment]
32bit binaries are still supported by windows 11. Is there something specific that doesn't work with the 32bit binary?

**Comment by itsmeboy0** [comment]
> 32bit binaries are still supported by windows 11. Is there something specific that doesn't work with the 32bit binary?

Nothing in particular. I just thought native 64-bit binaries work better on 64-bit systems. Additionally, ARM binaries for Windows would also be nice (would be better than x84/x64 emulation).

**Comment by Jacalz** [comment]
I think 64bit binaries would be a good addition and especially for arm64. It allows making use of newer instruction sets for better performance (see https://www.phoronix.com/scan.php?page=article&item=raspberrypi-32bit-64bit, not 100% related but the idea is the same). The amount of people running 32bit systems is also minimal and thus almost everyone will be able to run the 64bit binaries any way.

**Comment by Jacalz** [comment]
PR #80 should solve this. After that we just need a fresh new release :)
