### ISSUE TITLE
Distributing on npm

### ISSUE THREAD

**Issue by bakkot** [psanford/wormhole-william#87]
Hi! I'm ~planning on~ distributing the binaries from this project (with attribution) [on npm](https://www.npmjs.com/package/magic-wormhole), the package manager for JavaScript. This is a very convenient way for JS devs who already have node installed to use this project - it is just be a matter of running `npx magic-wormhole`, no manual downloads necessary.

(Yes, it's a little scary that everyone is so comfortable with this, but leave that aside.)

I wanted to give a heads up here in case you'd like me to take it down, or alternatively if you'd like to make this official, in which case I would be very happy to send a PR which adds a GitHub action which automatically publishes the new binaries whenever a GitHub release is created.

This is not the same as making it possible to use this project _from JavaScript_; that's more work (which I started [here](https://github.com/bakkot/magic-wormhole-js) but never got back to). It'll just be a convenient way of distributing the binaries.

**Comment by Jacalz** [comment]
It seems like something rather scary. My personal opinion is that there are better ways of distributing binaries. It almost seems like abusing how `npm` rather than a sensible way to distribute binaries but that's just my opinion :sweat_smile:

**Comment by bakkot** [comment]
It definitely is kind of abusing `npm`, but it's extremely convenient for people who already have `npm` installed. I'm not aware of any more convenient way of distributing binaries for multiple platforms, but maybe you have a suggestion?

**Comment by duckinator** [comment]
This seems like a weird way to solve the problem, but it would definitely be nice to have an easier way to get the binary downloads.

An approach I've seen before would be an easy-to-remember domain/subdomain which redirects to individual downloads -- e.g.  `/$FILE` (or `/download/$FILE`) to `https://github.com/psanford/wormhole-william/releases/latest/download/$FILE`.

(But that assumes the maintainer[s] consider the benefit to outweigh the monetary + effort cost, which may not be the case.)

**Comment by piegamesde** [comment]
> cross-platform tools for installing on all platforms

That's not how things work. Every platform has its own easiest way to install packages, which should be used.

**Comment by Jacalz** [comment]
I think this probably can be closed to be honest

**Comment by bakkot** [comment]
Yeah, this was just meant to be informative.
