### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by donpui** [psanford/wormhole-william#88]
In Least Authority, we have recently two apps based on wormhole-william and magic-wormhole protocols: [Destiny](https://github.com/LeastAuthority/destiny/) and [Winden.app](https://github.com/LeastAuthority/winden). We have made some changes in [our fork of wormhole-william](https://github.com/LeastAuthority/wormhole-william) during development (C bindings, WASM bindings, Security audit findings implemented, Hashcash, Websocket implementation, and various smaller fixes/ refactoring). We would like to upstream them and make it easier for other builders to use these changes.

[Differences] (https://github.com/psanford/wormhole-william/compare/master...LeastAuthority:wormhole-william:master)

There are few questions pop out:

- Is the upstream repo interested in having these changes? 
- What is the best way to upstream these changes as a whole or make them into separate different PRs?

We have some further plans to continue development and add more features, for example, dilation and multiple files sending support. We would be happy to contribute these changes too and even help with maintaining the upstream repository to boost usage.

**Comment by Jacalz** [comment]
I think the smaller cleanups and bug fixes would be quite quick and easy to upstream. The larger binding changes will likely take a lot more time to review. My personal opinion would be that it is best if you can divide it up into a few different PRs to make it easy to review.
